apiVersion: v1
kind: Pod
metadata:
  name: queryes
spec:
  containers:
  - env:
    - name: FILE
      value: /var/lib/docker/containers/a951f89437ad697417b0ee61ff46a67a9dcf1cb2726149127c1fddbbd12d984c/a951f89437ad697417b0ee61ff46a67a9dcf1cb2726149127c1fddbbd12d984c-json.log
    - name: ES
      value: elasticsearch-logging.kube-system:9200
    - name: TOTAL
      value: "300000"
    - name: INDEX
      value: logstash-2016.09.12
    - name: POD_NAME
      value: test-pd
    image: index.caicloud.io/caicloud/es_query
    name: esquery
    volumeMounts:
    - mountPath: /var/lib/docker/containers
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /var/lib/docker/containers
