apiVersion: v1
kind: Pod
metadata:
  name: test-services
spec:
  containers:
  - env:
    - name: SVC_NUMBER
      value: "30"
    image: index.caicloud.io/caicloud/services-test
    name: services-test
