apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - env:
    - name: runtime
      value: "600"
    - name: rate
      value: "500"
    image: index.caicloud.io/caicloud/loggenerator
    name: loggenerator
    volumeMounts:
    - mountPath: /var/lib/docker/containers
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /test/logs
  nodeName: i-sgiqmbxb
